-- ============================================ LAB 4 =========================================================
use untold

CREATE TABLE Tests (
	TestID int IDENTITY (1, 1) NOT NULL ,
	Name nvarchar (50) NOT NULL
) ON [PRIMARY]

CREATE TABLE Tables (
	TableID int IDENTITY (1, 1) NOT NULL ,
	Name nvarchar (50) NOT NULL
) ON [PRIMARY]

CREATE TABLE TestTables (
	TestID int NOT NULL ,
	TableID int NOT NULL ,
	NoOfRows int NOT NULL ,
    Position int NOT NULL
) ON [PRIMARY]

CREATE TABLE Views (
	ViewID int IDENTITY (1, 1) NOT NULL ,
	Name nvarchar (50) NOT NULL
) ON [PRIMARY]

CREATE TABLE TestViews (
	TestID int NOT NULL ,
	ViewID int NOT NULL
) ON [PRIMARY]

CREATE TABLE TestRuns (
	TestRunID int IDENTITY (1, 1) NOT NULL ,
	Description nvarchar (2000) NULL ,
	StartAt datetime NULL,
	EndAt datetime NULL
) ON [PRIMARY]

CREATE TABLE TestRunTables (
	TestRunID int NOT NULL ,
	TableID int NOT NULL ,
	StartAt datetime NOT NULL ,
	EndAt datetime NOT NULL
) ON [PRIMARY]

CREATE TABLE TestRunViews (
	TestRunID int NOT NULL ,
	ViewID int NOT NULL ,
	StartAt datetime NOT NULL ,
	EndAt datetime NOT NULL
) ON [PRIMARY]

ALTER TABLE Tests WITH NOCHECK
    ADD CONSTRAINT PK_Tests PRIMARY KEY CLUSTERED
	(TestID) ON [PRIMARY]

ALTER TABLE Tables WITH NOCHECK
	ADD CONSTRAINT PK_Tables PRIMARY KEY CLUSTERED
	(TableID) ON [PRIMARY]

ALTER TABLE TestTables WITH NOCHECK
	ADD CONSTRAINT PK_TestTables PRIMARY KEY CLUSTERED
	(TestID, TableID) ON [PRIMARY]

ALTER TABLE Views WITH NOCHECK
    ADD CONSTRAINT PK_Views PRIMARY KEY CLUSTERED
	(ViewID) ON [PRIMARY]

ALTER TABLE TestViews WITH NOCHECK
	ADD CONSTRAINT PK_TestViews PRIMARY KEY CLUSTERED
	(TestID, ViewID) ON [PRIMARY]

ALTER TABLE TestRuns WITH NOCHECK
	ADD CONSTRAINT PK_TestRuns PRIMARY KEY CLUSTERED
	(TestRunID) ON [PRIMARY]

ALTER TABLE TestRunTables WITH NOCHECK
	ADD CONSTRAINT PK_TestRunTables PRIMARY KEY CLUSTERED
	(TestRunID, TableID) ON [PRIMARY]

ALTER TABLE TestRunViews WITH NOCHECK
	ADD CONSTRAINT PK_TestRunViews PRIMARY KEY CLUSTERED
	(TestRunID,	ViewID) ON [PRIMARY]

ALTER TABLE TestTables
	ADD CONSTRAINT FK_TestTables_Tables FOREIGN KEY
	(TableID) REFERENCES Tables (TableID) ON DELETE CASCADE ON UPDATE CASCADE ,
	CONSTRAINT FK_TestTables_Tests FOREIGN KEY
	(TestID) REFERENCES Tests (TestID) ON DELETE CASCADE ON UPDATE CASCADE

ALTER TABLE TestViews
    ADD CONSTRAINT FK_TestViews_Tests FOREIGN KEY
	(TestID) REFERENCES Tests (TestID),
	CONSTRAINT FK_TestViews_Views FOREIGN KEY
	(ViewID) REFERENCES Views (ViewID)

ALTER TABLE TestRunTables
    ADD CONSTRAINT FK_TestRunTables_Tables FOREIGN KEY
	(TableID) REFERENCES Tables (TableID) ON DELETE CASCADE ON UPDATE CASCADE ,
	CONSTRAINT FK_TestRunTables_TestRuns FOREIGN KEY
	(TestRunID) REFERENCES TestRuns (TestRunID) ON DELETE CASCADE ON UPDATE CASCADE

ALTER TABLE TestRunViews
	ADD CONSTRAINT FK_TestRunViews_TestRuns FOREIGN KEY
	(TestRunID) REFERENCES TestRuns (TestRunID) ON DELETE CASCADE ON UPDATE CASCADE ,
	CONSTRAINT FK_TestRunViews_Views FOREIGN KEY
	(ViewID) REFERENCES Views (ViewID) ON DELETE CASCADE ON UPDATE CASCADE


ALTER TABLE works_at
    ADD CONSTRAINT PK_works_at PRIMARY KEY (CNP, DID)
