# Generated by Django 4.1.7 on 2023-03-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0006_remove_song_label_performson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performson',
            name='label',
        ),
        migrations.RemoveField(
            model_name='song',
            name='duration',
        ),
        migrations.AddField(
            model_name='performson',
            name='duration',
            field=models.CharField(default='00:00', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='composer',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
