# Generated by Django 4.1.7 on 2023-04-09 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0007_remove_performson_label_remove_song_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='CNP',
        ),
    ]
