# Generated by Django 4.1.7 on 2023-04-09 21:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0012_alter_album_year_of_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performson',
            name='duration',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('..:..')]),
        ),
    ]
