# Generated by Django 4.2 on 2023-05-01 13:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=100)),
                ('real_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PerformsOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_of_views', models.IntegerField()),
                ('duration', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('..:..')])),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Music_app.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=100)),
                ('composer', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('year_of_release', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2023)])),
                ('artists', models.ManyToManyField(through='Music_app.PerformsOn', to='Music_app.artist')),
            ],
        ),
        migrations.AddField(
            model_name='performson',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Music_app.song'),
        ),
        migrations.AddField(
            model_name='artist',
            name='songs',
            field=models.ManyToManyField(through='Music_app.PerformsOn', to='Music_app.song'),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_title', models.CharField(max_length=100)),
                ('nr_of_tracks', models.IntegerField()),
                ('label', models.CharField(max_length=100)),
                ('year_of_release', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2023)])),
                ('main_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='Music_app.artist')),
            ],
        ),
    ]
