# Generated by Django 4.1.7 on 2023-03-13 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0003_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_title', models.CharField(max_length=100)),
                ('nr_of_tracks', models.PositiveSmallIntegerField()),
                ('label', models.CharField(max_length=100)),
                ('year_of_release', models.PositiveSmallIntegerField()),
                ('main_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Music.artist')),
            ],
        ),
    ]
