# Generated by Django 4.1.7 on 2023-04-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0013_alter_performson_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performson',
            old_name='artist_id',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='performson',
            old_name='song_id',
            new_name='song',
        ),
        migrations.AddField(
            model_name='artist',
            name='songs',
            field=models.ManyToManyField(through='Music.PerformsOn', to='Music.song'),
        ),
        migrations.AddField(
            model_name='song',
            name='artists',
            field=models.ManyToManyField(through='Music.PerformsOn', to='Music.artist'),
        ),
    ]
