# Generated by Django 4.1.7 on 2023-04-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0015_remove_artist_songs_remove_song_artists'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='songs',
            field=models.ManyToManyField(through='Music.PerformsOn', to='Music.song'),
        ),
        migrations.AddField(
            model_name='song',
            name='artists',
            field=models.ManyToManyField(through='Music.PerformsOn', to='Music.artist'),
        ),
    ]
