# Generated by Django 4.1.7 on 2023-04-22 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0016_artist_songs_song_artists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='year_of_release',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2023)]),
        ),
    ]
