# Generated by Django 4.1.7 on 2023-03-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_song', models.PositiveSmallIntegerField()),
                ('artist', models.CharField(max_length=100)),
                ('song_name', models.CharField(max_length=100)),
                ('producer', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('year_of_release', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
