# Generated by Django 4.1.7 on 2023-03-06 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Song', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='producer',
            new_name='label',
        ),
    ]
