# Generated by Django 4.1.7 on 2023-03-13 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0004_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='main_artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='Music.artist'),
        ),
        migrations.AlterField(
            model_name='album',
            name='nr_of_tracks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='album',
            name='year_of_release',
            field=models.IntegerField(),
        ),
    ]
