# Generated by Django 4.1.7 on 2023-03-20 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0005_alter_album_main_artist_alter_album_nr_of_tracks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='label',
        ),
        migrations.CreateModel(
            name='PerformsOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('nr_of_views', models.IntegerField()),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Music.artist')),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Music.song')),
            ],
        ),
    ]
